//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class LogHeThong_6_2016
{
    public int id_loghethong { get; set; }
    public string noidung { get; set; }
    public Nullable<int> id_taikhoan { get; set; }
    public Nullable<System.DateTime> ngaytao { get; set; }
    public string type { get; set; }
    public string vitrihoatdong { get; set; }
    public string tablename { get; set; }
}

public partial class LogHeThong_6_2017
{
    public int id_loghethong { get; set; }
    public string noidung { get; set; }
    public Nullable<int> id_taikhoan { get; set; }
    public Nullable<System.DateTime> ngaytao { get; set; }
    public string type { get; set; }
    public string vitrihoatdong { get; set; }
    public string tablename { get; set; }
}

public partial class Menu_Client
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Menu_Client()
    {
        this.tbl_BaiVietTrangGioiThieu = new HashSet<tbl_BaiVietTrangGioiThieu>();
        this.tbl_ChuyenMucLuaChon = new HashSet<tbl_ChuyenMucLuaChon>();
        this.tbl_ThuVienClient = new HashSet<tbl_ThuVienClient>();
        this.tbl_VanBan = new HashSet<tbl_VanBan>();
        this.tbl_VanBan1 = new HashSet<tbl_VanBan>();
        this.tbl_Vitribv = new HashSet<tbl_Vitribv>();
        this.Vitri_Menu = new HashSet<Vitri_Menu>();
    }

    public int id_danhmuc { get; set; }
    public string tendanhmuc { get; set; }
    public string link_danhmuc { get; set; }
    public Nullable<int> trangthai { get; set; }
    public Nullable<int> sothutu { get; set; }
    public Nullable<int> idParent { get; set; }
    public string shortcode { get; set; }
    public string duongdan { get; set; }
    public string icon { get; set; }
    public Nullable<int> socapdanhmuc { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_BaiVietTrangGioiThieu> tbl_BaiVietTrangGioiThieu { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_ChuyenMucLuaChon> tbl_ChuyenMucLuaChon { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_ThuVienClient> tbl_ThuVienClient { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_VanBan> tbl_VanBan { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_VanBan> tbl_VanBan1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_Vitribv> tbl_Vitribv { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Vitri_Menu> Vitri_Menu { get; set; }
}

public partial class NhomAdmin
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public NhomAdmin()
    {
        this.NhomQuyen = new HashSet<NhomQuyen>();
        this.TaiKhoan = new HashSet<TaiKhoan>();
    }

    public int id_nhomadmin { get; set; }
    public string tennhom { get; set; }
    public Nullable<System.DateTime> ngaytao { get; set; }
    public Nullable<bool> trangthai { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<NhomQuyen> NhomQuyen { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TaiKhoan> TaiKhoan { get; set; }
}

public partial class NhomQuyen
{
    public int id_nhomquyen { get; set; }
    public Nullable<int> id_menu { get; set; }
    public Nullable<int> id_nhomadmin { get; set; }
    public Nullable<bool> xem { get; set; }
    public Nullable<bool> them { get; set; }
    public Nullable<bool> sua { get; set; }
    public Nullable<bool> xoa { get; set; }
    public Nullable<bool> trangthai { get; set; }

    public virtual NhomAdmin NhomAdmin { get; set; }
    public virtual tbl_Menu tbl_Menu { get; set; }
}

public partial class QuanLyBanner
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public QuanLyBanner()
    {
        this.tbl_ChuKyHienThiBanner = new HashSet<tbl_ChuKyHienThiBanner>();
    }

    public int id_quanlybanner { get; set; }
    public string tenbanner { get; set; }
    public string mimetype { get; set; }
    public Nullable<System.DateTime> ngayupload { get; set; }
    public Nullable<int> id_taikhoan { get; set; }
    public Nullable<int> trangthai { get; set; }
    public string vitri { get; set; }
    public string linkbanner { get; set; }
    public string target { get; set; }
    public string duongdanfile { get; set; }
    public string type { get; set; }

    public virtual TaiKhoan TaiKhoan { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_ChuKyHienThiBanner> tbl_ChuKyHienThiBanner { get; set; }
}

public partial class QuanLyFileUpload
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public QuanLyFileUpload()
    {
        this.tbl_QuyenSuDungFile = new HashSet<tbl_QuyenSuDungFile>();
    }

    public int id_quanlyfileupload { get; set; }
    public string tenfile { get; set; }
    public string mimetype { get; set; }
    public Nullable<System.DateTime> ngayupload { get; set; }
    public Nullable<int> id_quanlythumuc { get; set; }
    public Nullable<int> id_taikhoan { get; set; }
    public string dungluongfile { get; set; }
    public Nullable<bool> trangthai { get; set; }
    public string duongdanfile { get; set; }

    public virtual QuanLyThuMuc QuanLyThuMuc { get; set; }
    public virtual TaiKhoan TaiKhoan { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_QuyenSuDungFile> tbl_QuyenSuDungFile { get; set; }
}

public partial class QuanLyThuMuc
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public QuanLyThuMuc()
    {
        this.QuanLyFileUpload = new HashSet<QuanLyFileUpload>();
    }

    public int id_quanlythumuc { get; set; }
    public string tenthumuc { get; set; }
    public Nullable<System.DateTime> ngaytao { get; set; }
    public Nullable<int> id_taikhoan { get; set; }
    public Nullable<bool> trangthai { get; set; }
    public Nullable<int> idParents { get; set; }
    public string icon { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<QuanLyFileUpload> QuanLyFileUpload { get; set; }
    public virtual TaiKhoan TaiKhoan { get; set; }
}

public partial class TaiKhoan
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TaiKhoan()
    {
        this.QuanLyBanner = new HashSet<QuanLyBanner>();
        this.QuanLyFileUpload = new HashSet<QuanLyFileUpload>();
        this.QuanLyThuMuc = new HashSet<QuanLyThuMuc>();
        this.tbl_Baiviet = new HashSet<tbl_Baiviet>();
        this.tbl_CauhoiTraLoi = new HashSet<tbl_CauhoiTraLoi>();
        this.tbl_CauhoiTraLoi1 = new HashSet<tbl_CauhoiTraLoi>();
        this.tbl_LogHeThong = new HashSet<tbl_LogHeThong>();
        this.tbl_LogResetMatKhau = new HashSet<tbl_LogResetMatKhau>();
        this.tbl_QuyenSuDungFile = new HashSet<tbl_QuyenSuDungFile>();
        this.tbl_ThuVienClient = new HashSet<tbl_ThuVienClient>();
    }

    public int id_taikhoan { get; set; }
    public string taikhoan1 { get; set; }
    public string matkhau { get; set; }
    public string tendaydu { get; set; }
    public string email { get; set; }
    public string sodienthoai { get; set; }
    public Nullable<bool> trangthaitk { get; set; }
    public Nullable<int> id_nhomadmin { get; set; }
    public Nullable<System.DateTime> ngaytao { get; set; }
    public Nullable<int> loaitaikhoan { get; set; }
    public string avatar { get; set; }

    public virtual NhomAdmin NhomAdmin { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<QuanLyBanner> QuanLyBanner { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<QuanLyFileUpload> QuanLyFileUpload { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<QuanLyThuMuc> QuanLyThuMuc { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_Baiviet> tbl_Baiviet { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_CauhoiTraLoi> tbl_CauhoiTraLoi { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_CauhoiTraLoi> tbl_CauhoiTraLoi1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_LogHeThong> tbl_LogHeThong { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_LogResetMatKhau> tbl_LogResetMatKhau { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_QuyenSuDungFile> tbl_QuyenSuDungFile { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_ThuVienClient> tbl_ThuVienClient { get; set; }
}

public partial class TB_ThongKe
{
    public int MaTB { get; set; }
    public System.DateTime ThoiGian { get; set; }
    public long SoTruyCap { get; set; }
}

public partial class tbl_Baiviet
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_Baiviet()
    {
        this.tbl_Vitribv = new HashSet<tbl_Vitribv>();
    }

    public int id_baiviet { get; set; }
    public string tieude { get; set; }
    public string gioithieu { get; set; }
    public string noidung { get; set; }
    public string tacgia { get; set; }
    public Nullable<System.DateTime> ngaytao { get; set; }
    public string tag { get; set; }
    public Nullable<int> trangthaibaiviet { get; set; }
    public string avatar { get; set; }
    public Nullable<int> id_taikhoan { get; set; }
    public Nullable<int> idRoot { get; set; }
    public string tenRoot { get; set; }
    public string linkbaiviet { get; set; }

    public virtual TaiKhoan TaiKhoan { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_Vitribv> tbl_Vitribv { get; set; }
}

public partial class tbl_BaiVietTrangGioiThieu
{
    public int id_baivietGT { get; set; }
    public string noidung { get; set; }
    public Nullable<bool> trangthai { get; set; }
    public Nullable<int> id_danhmuc { get; set; }
    public string linkbaiGT { get; set; }
    public Nullable<System.DateTime> ngaytao { get; set; }

    public virtual Menu_Client Menu_Client { get; set; }
}

public partial class tbl_BieuDo
{
    public int id_bieudo { get; set; }
    public string tenbieudo { get; set; }
    public Nullable<int> trangthai { get; set; }
    public Nullable<int> tuthoigian { get; set; }
    public Nullable<int> denthoigian { get; set; }
    public Nullable<int> id_loaibieudo { get; set; }
    public Nullable<int> id_donvitg { get; set; }

    public virtual tbl_donvithoigianbieudo tbl_donvithoigianbieudo { get; set; }
    public virtual tbl_Loaibieudo tbl_Loaibieudo { get; set; }
}

public partial class tbl_CapBac
{
    public int id_capbac { get; set; }
    public string quanham { get; set; }
    public Nullable<bool> trangthai { get; set; }
}

public partial class tbl_CauhoiTraLoi
{
    public int id_cauhoitraloi { get; set; }
    public string cauhoi { get; set; }
    public string traloi { get; set; }
    public Nullable<System.DateTime> ngayhoi { get; set; }
    public Nullable<System.DateTime> ngaytraloi { get; set; }
    public Nullable<int> trangthai { get; set; }
    public Nullable<int> luotxem { get; set; }
    public Nullable<int> id_nguoitraloi { get; set; }
    public Nullable<int> id_chuyenmuc { get; set; }
    public string loaicauhoi { get; set; }
    public Nullable<int> id_nguoihoi { get; set; }
    public string filedinhkem { get; set; }
    public Nullable<bool> statusRepQuestion { get; set; }
    public string fileQuestion { get; set; }
    public string linkcauhoi { get; set; }
    public string tieudecauhoi { get; set; }

    public virtual TaiKhoan TaiKhoan { get; set; }
    public virtual TaiKhoan TaiKhoan1 { get; set; }
    public virtual tbl_ChuyenMucLuaChon tbl_ChuyenMucLuaChon { get; set; }
}

public partial class tbl_ChiTietThuVien
{
    public int id_chitietthuvien { get; set; }
    public string duongdanfile { get; set; }
    public Nullable<int> id_thuvien { get; set; }
    public Nullable<int> trangthai { get; set; }
    public Nullable<System.DateTime> ngaytao { get; set; }
    public string filetype { get; set; }

    public virtual tbl_ThuVienClient tbl_ThuVienClient { get; set; }
}

public partial class tbl_ChuKyHienThiBanner
{
    public int id_chitietchukyhienthi { get; set; }
    public Nullable<int> id_quanlybanner { get; set; }
    public Nullable<int> trangthai { get; set; }
    public Nullable<System.DateTime> tungay { get; set; }
    public Nullable<System.DateTime> denngay { get; set; }
    public Nullable<int> mucdouutien { get; set; }

    public virtual QuanLyBanner QuanLyBanner { get; set; }
}

public partial class tbl_ChuKyHienThiQuangCao
{
    public int id_chukyhienthiquangcao { get; set; }
    public Nullable<System.TimeSpan> tuthoigian { get; set; }
    public Nullable<System.TimeSpan> denthoigian { get; set; }
    public string tuthu { get; set; }
    public string denthu { get; set; }
    public Nullable<int> id_chukyhienthi { get; set; }
    public Nullable<int> id_quangcao { get; set; }
    public Nullable<bool> trangthai { get; set; }
    public Nullable<int> id_vitriquangcao { get; set; }

    public virtual tbl_quangcao tbl_quangcao { get; set; }
}

public partial class tbl_ChuyenMucLuaChon
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_ChuyenMucLuaChon()
    {
        this.tbl_CauhoiTraLoi = new HashSet<tbl_CauhoiTraLoi>();
        this.tbl_TinBaoCongDan = new HashSet<tbl_TinBaoCongDan>();
    }

    public int id_chuyenmuc { get; set; }
    public string tenchuyenmuc { get; set; }
    public Nullable<int> id_danhmuc { get; set; }
    public Nullable<bool> trangthai { get; set; }
    public string linkchuyenmuc { get; set; }

    public virtual Menu_Client Menu_Client { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_CauhoiTraLoi> tbl_CauhoiTraLoi { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_TinBaoCongDan> tbl_TinBaoCongDan { get; set; }
}

public partial class tbl_Danhsachbanglog
{
    public int id_danhsach { get; set; }
    public string tenbanglog { get; set; }
    public Nullable<System.DateTime> ngaytao { get; set; }
    public Nullable<int> trangthai { get; set; }
    public Nullable<System.DateTime> ngayketthuc { get; set; }
}

public partial class tbl_DanhSachCanBo
{
    public int id_dscanbo { get; set; }
    public string tencanbo { get; set; }
    public Nullable<int> id_chucvu { get; set; }
    public string donvicongtac { get; set; }
    public string thongtinlienhe { get; set; }
    public string anhdaidien { get; set; }
    public Nullable<int> trangthaicanbo { get; set; }
    public string quanham { get; set; }
    public Nullable<System.DateTime> ngaysinh { get; set; }
    public string quequan { get; set; }

    public virtual tbl_DanhSachChucVu tbl_DanhSachChucVu { get; set; }
}

public partial class tbl_DanhSachChucVu
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_DanhSachChucVu()
    {
        this.tbl_DanhSachCanBo = new HashSet<tbl_DanhSachCanBo>();
    }

    public int id_chucvu { get; set; }
    public string tenchucvu { get; set; }
    public Nullable<bool> trangthai { get; set; }
    public Nullable<int> idParents { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_DanhSachCanBo> tbl_DanhSachCanBo { get; set; }
}

public partial class tbl_DanhSachTongDai
{
    public int id_dstongdai { get; set; }
    public string email { get; set; }
    public string sodienthoai { get; set; }
    public Nullable<int> trangthai { get; set; }
    public Nullable<int> id_taikhoan { get; set; }
    public string diachi { get; set; }
    public string tendonvi { get; set; }
    public string mota { get; set; }
    public Nullable<System.DateTime> ngaytao { get; set; }
}

public partial class tbl_DapAnThamDo
{
    public int id_dapanthamdo { get; set; }
    public string noidungtraloi { get; set; }
    public Nullable<int> id_cauhoithamdo { get; set; }
    public Nullable<int> demcautraloi { get; set; }
    public Nullable<bool> trangthai { get; set; }

    public virtual tbl_ThamDoYKien tbl_ThamDoYKien { get; set; }
}

public partial class tbl_DatLich
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_DatLich()
    {
        this.tbl_Vitribv = new HashSet<tbl_Vitribv>();
    }

    public int id_datlich { get; set; }
    public Nullable<System.DateTime> ngaydang { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_Vitribv> tbl_Vitribv { get; set; }
}

public partial class tbl_DonVicongTac
{
    public int id_donvi { get; set; }
    public string donvicongtac { get; set; }
    public Nullable<bool> trangthai { get; set; }
    public string diachi { get; set; }
}

public partial class tbl_donvithoigianbieudo
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_donvithoigianbieudo()
    {
        this.tbl_BieuDo = new HashSet<tbl_BieuDo>();
    }

    public int id_donvitg { get; set; }
    public string tendonvi { get; set; }
    public Nullable<bool> trangthai { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_BieuDo> tbl_BieuDo { get; set; }
}

public partial class tbl_Hinhthucphamtoi
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_Hinhthucphamtoi()
    {
        this.tbl_Hosovuan = new HashSet<tbl_Hosovuan>();
    }

    public int id_hinhthucphamtoi { get; set; }
    public string hinhthucphamtoi { get; set; }
    public Nullable<bool> trangthai { get; set; }
    public Nullable<bool> trangthaithongke { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_Hosovuan> tbl_Hosovuan { get; set; }
}

public partial class tbl_HinhthucTraLoi
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_HinhthucTraLoi()
    {
        this.tbl_ThamDoYKien = new HashSet<tbl_ThamDoYKien>();
    }

    public int id_hinhthuctraloi { get; set; }
    public string hinhthuctraloi { get; set; }
    public Nullable<bool> trangthai { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_ThamDoYKien> tbl_ThamDoYKien { get; set; }
}

public partial class tbl_Hosovuan
{
    public int id_hoso { get; set; }
    public Nullable<int> id_toipham { get; set; }
    public Nullable<int> id_hinhthucphamtoi { get; set; }
    public Nullable<System.DateTime> ngayluuhoso { get; set; }
    public Nullable<int> tinhtranghoso { get; set; }

    public virtual tbl_Hinhthucphamtoi tbl_Hinhthucphamtoi { get; set; }
    public virtual tbl_Thongtintoipham tbl_Thongtintoipham { get; set; }
}

public partial class tbl_HuongDanSuLyTinhHuong
{
    public int id_huongdan { get; set; }
    public string tinhhuong { get; set; }
    public string cachxuly { get; set; }
    public Nullable<int> trangthai { get; set; }
    public Nullable<int> id_taikhoan { get; set; }
    public Nullable<System.DateTime> ngaytao { get; set; }
    public string tieude { get; set; }
    public string linktinhhuong { get; set; }
}

public partial class tbl_LichHienThiThamDoYKien
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_LichHienThiThamDoYKien()
    {
        this.tbl_ThamDoYKien = new HashSet<tbl_ThamDoYKien>();
    }

    public int id_lich { get; set; }
    public Nullable<System.DateTime> tungay { get; set; }
    public Nullable<System.DateTime> denngay { get; set; }
    public Nullable<bool> trangthai { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_ThamDoYKien> tbl_ThamDoYKien { get; set; }
}

public partial class tbl_LienKetHopTac
{
    public int id_lienkethoptac { get; set; }
    public string tendoitac { get; set; }
    public string avatar { get; set; }
    public string linkdiachi { get; set; }
    public string thongtindoitac { get; set; }
    public string target { get; set; }
    public Nullable<int> trangthai { get; set; }
}

public partial class tbl_Loaibieudo
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_Loaibieudo()
    {
        this.tbl_BieuDo = new HashSet<tbl_BieuDo>();
    }

    public int id_loaibieudo { get; set; }
    public string tenloaibieudo { get; set; }
    public Nullable<bool> trangthai { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_BieuDo> tbl_BieuDo { get; set; }
}

public partial class tbl_LogHeThong
{
    public int id_loghethong { get; set; }
    public string noidung { get; set; }
    public Nullable<int> id_taikhoan { get; set; }
    public Nullable<System.DateTime> ngaytao { get; set; }
    public string type { get; set; }
    public string vitrihoatdong { get; set; }
    public string tablename { get; set; }

    public virtual TaiKhoan TaiKhoan { get; set; }
}

public partial class tbl_LogResetMatKhau
{
    public int id_LogReset { get; set; }
    public Nullable<int> id_taikhoan { get; set; }
    public Nullable<System.DateTime> ngaytao { get; set; }
    public Nullable<bool> trangthai { get; set; }
    public string malink { get; set; }
    public string matkhaumoi { get; set; }
    public string matkhaucu { get; set; }

    public virtual TaiKhoan TaiKhoan { get; set; }
}

public partial class tbl_logtraloithamdo
{
    public int id_log { get; set; }
    public Nullable<int> id_cauhoithamdo { get; set; }
    public Nullable<System.DateTime> ngaytraloi { get; set; }
    public string ip { get; set; }
}

public partial class tbl_Menu
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_Menu()
    {
        this.NhomQuyen = new HashSet<NhomQuyen>();
    }

    public int id_menu { get; set; }
    public string tenmenu { get; set; }
    public string linkmenu { get; set; }
    public string vitri { get; set; }
    public Nullable<int> trangthai { get; set; }
    public Nullable<int> idParent { get; set; }
    public Nullable<int> id_taikhoan { get; set; }
    public Nullable<int> sothutu { get; set; }
    public string icon { get; set; }
    public string duongdan { get; set; }
    public string shortcode { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<NhomQuyen> NhomQuyen { get; set; }
}

public partial class tbl_quangcao
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_quangcao()
    {
        this.tbl_ChuKyHienThiQuangCao = new HashSet<tbl_ChuKyHienThiQuangCao>();
    }

    public int id_quangcao { get; set; }
    public string tenquangcao { get; set; }
    public string donvidat { get; set; }
    public Nullable<int> trangthaihienthi { get; set; }
    public string thongtin { get; set; }
    public string manguon { get; set; }
    public string vitridatqc { get; set; }
    public Nullable<int> tilexuathien { get; set; }
    public Nullable<System.DateTime> ngaydang { get; set; }
    public Nullable<System.DateTime> ngaydung { get; set; }
    public Nullable<int> id_taikhoan { get; set; }
    public Nullable<int> id_quanlythumuc { get; set; }
    public Nullable<bool> trangthai { get; set; }
    public Nullable<int> id_vitriquangcao { get; set; }
    public string linkquangcao { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_ChuKyHienThiQuangCao> tbl_ChuKyHienThiQuangCao { get; set; }
    public virtual tbl_VitriQuangCao tbl_VitriQuangCao { get; set; }
}

public partial class tbl_QuyenSuDungFile
{
    public int id_quyensd { get; set; }
    public Nullable<int> id_quanlyfileupload { get; set; }
    public Nullable<int> id_taikhoan { get; set; }
    public string kieufile { get; set; }

    public virtual QuanLyFileUpload QuanLyFileUpload { get; set; }
    public virtual TaiKhoan TaiKhoan { get; set; }
}

public partial class tbl_ThamDoYKien
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_ThamDoYKien()
    {
        this.tbl_DapAnThamDo = new HashSet<tbl_DapAnThamDo>();
    }

    public int id_cauhoithamdo { get; set; }
    public string cauhoi { get; set; }
    public Nullable<int> id_hinhthuctraloi { get; set; }
    public Nullable<int> id_taikhoan { get; set; }
    public Nullable<int> id_lich { get; set; }
    public Nullable<int> trangthai { get; set; }
    public Nullable<int> tongsocautraloi { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_DapAnThamDo> tbl_DapAnThamDo { get; set; }
    public virtual tbl_HinhthucTraLoi tbl_HinhthucTraLoi { get; set; }
    public virtual tbl_LichHienThiThamDoYKien tbl_LichHienThiThamDoYKien { get; set; }
}

public partial class tbl_Thongtinthoitiet
{
    public int id_STT { get; set; }
    public string ClassName { get; set; }
    public string CodeId { get; set; }
    public string Date { get; set; }
    public string DayNumber { get; set; }
    public string DayText { get; set; }
    public string FullDate { get; set; }
    public Nullable<int> High { get; set; }
    public Nullable<int> Humidity { get; set; }
    public Nullable<int> Id { get; set; }
    public string LocationName { get; set; }
    public Nullable<int> Low { get; set; }
    public string Status { get; set; }
    public string Sunrise { get; set; }
    public string Sunset { get; set; }
    public Nullable<int> Temperature { get; set; }
    public string Time { get; set; }
    public Nullable<System.DateTime> WeatherDate { get; set; }
    public Nullable<double> Wind { get; set; }
    public Nullable<int> id_TinhThanh { get; set; }

    public virtual tbl_TinhThanh tbl_TinhThanh { get; set; }
}

public partial class tbl_Thongtintoipham
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_Thongtintoipham()
    {
        this.tbl_Hosovuan = new HashSet<tbl_Hosovuan>();
    }

    public int id_toipham { get; set; }
    public string hoten { get; set; }
    public string hokhauthuongtru { get; set; }
    public string sochungminhthu { get; set; }
    public string quequan { get; set; }
    public string bietdanh { get; set; }
    public System.DateTime ngaysinh { get; set; }
    public Nullable<bool> trangthai { get; set; }
    public string hinhanh { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_Hosovuan> tbl_Hosovuan { get; set; }
}

public partial class tbl_ThuVienClient
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_ThuVienClient()
    {
        this.tbl_ChiTietThuVien = new HashSet<tbl_ChiTietThuVien>();
    }

    public int id_thuvien { get; set; }
    public string tieude { get; set; }
    public string gioithieu { get; set; }
    public string noidung { get; set; }
    public Nullable<System.DateTime> ngayupload { get; set; }
    public string tacgia { get; set; }
    public string loaithuvien { get; set; }
    public Nullable<int> id_taikhoan { get; set; }
    public Nullable<int> trangthaithuvien { get; set; }
    public Nullable<int> id_danhmuc { get; set; }
    public string linlthuvien { get; set; }
    public Nullable<int> luotxem { get; set; }

    public virtual Menu_Client Menu_Client { get; set; }
    public virtual TaiKhoan TaiKhoan { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_ChiTietThuVien> tbl_ChiTietThuVien { get; set; }
}

public partial class tbl_TinBaoCongDan
{
    public int id_tinbao { get; set; }
    public string hoten { get; set; }
    public string email { get; set; }
    public string dienthoai { get; set; }
    public string diachi { get; set; }
    public string diaban { get; set; }
    public string noidungtinbao { get; set; }
    public Nullable<int> trangthaihienthi { get; set; }
    public Nullable<System.DateTime> ngaygui { get; set; }
    public Nullable<System.DateTime> ngayxem { get; set; }
    public Nullable<int> id_chuyenmuc { get; set; }
    public string tieude { get; set; }
    public string linktinbao { get; set; }
    public Nullable<bool> trangthaixem { get; set; }

    public virtual tbl_ChuyenMucLuaChon tbl_ChuyenMucLuaChon { get; set; }
}

public partial class tbl_TinhThanh
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_TinhThanh()
    {
        this.tbl_Thongtinthoitiet = new HashSet<tbl_Thongtinthoitiet>();
    }

    public int id_TinhThanh { get; set; }
    public string TenTinh { get; set; }
    public string codeID { get; set; }
    public string ngayluu { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_Thongtinthoitiet> tbl_Thongtinthoitiet { get; set; }
}

public partial class tbl_VanBan
{
    public int id_vanban { get; set; }
    public string tenvanban { get; set; }
    public string sokyhieu { get; set; }
    public Nullable<System.DateTime> ngaybanhanh { get; set; }
    public string trichyeu { get; set; }
    public string noidung { get; set; }
    public Nullable<int> id_taikhoan { get; set; }
    public Nullable<int> trangthai { get; set; }
    public Nullable<System.DateTime> ngaytao { get; set; }
    public string kieuvanban { get; set; }
    public string icon { get; set; }
    public string duongdanfile { get; set; }
    public string linkvanban { get; set; }
    public Nullable<int> id_coquanbanhanh { get; set; }
    public Nullable<int> id_loaivanban { get; set; }

    public virtual Menu_Client Menu_Client { get; set; }
    public virtual Menu_Client Menu_Client1 { get; set; }
}

public partial class tbl_Vitribv
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_Vitribv()
    {
        this.tbl_Ykienbandoc = new HashSet<tbl_Ykienbandoc>();
    }

    public int id_vitribv { get; set; }
    public Nullable<int> id_baiviet { get; set; }
    public Nullable<int> id_danhmuc { get; set; }
    public Nullable<int> soluotview { get; set; }
    public Nullable<int> soluotlike { get; set; }
    public Nullable<int> trangthaibaiviet { get; set; }
    public string linkbaiviet { get; set; }
    public Nullable<int> id_datlich { get; set; }
    public Nullable<System.DateTime> ngaydang { get; set; }

    public virtual Menu_Client Menu_Client { get; set; }
    public virtual tbl_Baiviet tbl_Baiviet { get; set; }
    public virtual tbl_DatLich tbl_DatLich { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_Ykienbandoc> tbl_Ykienbandoc { get; set; }
}

public partial class tbl_VitriQuangCao
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_VitriQuangCao()
    {
        this.tbl_quangcao = new HashSet<tbl_quangcao>();
    }

    public int id_vitriquangcao { get; set; }
    public string name { get; set; }
    public string type { get; set; }
    public string mota { get; set; }
    public Nullable<bool> show { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tbl_quangcao> tbl_quangcao { get; set; }
}

public partial class tbl_ViTriVanBan
{
    public int id_vitrivanban { get; set; }
    public Nullable<int> id_vanban { get; set; }
    public Nullable<int> id_danhmuc { get; set; }
    public Nullable<int> soluotview { get; set; }
    public Nullable<int> soluotlike { get; set; }
    public Nullable<int> soluotdowload { get; set; }
    public Nullable<int> trangthaivb { get; set; }
    public string linkvanban { get; set; }
    public Nullable<System.DateTime> ngaydang { get; set; }
}

public partial class tbl_Ykienbandoc
{
    public int id_ykienbandoc { get; set; }
    public string tennguoidang { get; set; }
    public Nullable<System.DateTime> thoigiandang { get; set; }
    public string noidung { get; set; }
    public Nullable<int> id_vitribv { get; set; }
    public Nullable<int> soluotview { get; set; }
    public Nullable<int> soluotlike { get; set; }
    public Nullable<int> trangthai { get; set; }
    public string email { get; set; }
    public Nullable<int> idParentRep { get; set; }
    public Nullable<int> trangthaihienthi { get; set; }

    public virtual tbl_Vitribv tbl_Vitribv { get; set; }
}

public partial class Vitri_Menu
{
    public int id_vitrimenu { get; set; }
    public Nullable<bool> menutop { get; set; }
    public Nullable<bool> menubottom { get; set; }
    public Nullable<bool> trangthai { get; set; }
    public Nullable<int> id_danhmuc { get; set; }
    public Nullable<bool> menuright { get; set; }

    public virtual Menu_Client Menu_Client { get; set; }
}

public partial class SP_DANHSACHTONGDAI_Result
{
    public int id_dstongdai { get; set; }
    public string email { get; set; }
    public string sodienthoai { get; set; }
    public Nullable<int> trangthai { get; set; }
    public Nullable<int> id_taikhoan { get; set; }
    public string diachi { get; set; }
    public string tendonvi { get; set; }
    public string mota { get; set; }
    public Nullable<System.DateTime> ngaytao { get; set; }
    public Nullable<long> X { get; set; }
}

public partial class sp_helpdiagramdefinition_Result
{
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class sp_helpdiagrams_Result
{
    public string Database { get; set; }
    public string Name { get; set; }
    public int ID { get; set; }
    public string Owner { get; set; }
    public int OwnerID { get; set; }
}

public partial class sp_loadall_tintucsukien_Result
{
    public int id_baiviet { get; set; }
    public string tieude { get; set; }
    public string gioithieu { get; set; }
    public string noidung { get; set; }
    public string tacgia { get; set; }
    public Nullable<System.DateTime> ngaytao { get; set; }
    public string tag { get; set; }
    public Nullable<int> trangthaibaiviet { get; set; }
    public string avatar { get; set; }
    public Nullable<int> id_taikhoan { get; set; }
    public Nullable<int> idRoot { get; set; }
    public string tenRoot { get; set; }
    public string linkbaiviet { get; set; }
    public Nullable<long> X { get; set; }
}

public partial class SP_LOADDANHSACHBAIVIET_Result
{
    public int id_vitribv { get; set; }
    public Nullable<int> id_baiviet { get; set; }
    public Nullable<int> id_danhmuc { get; set; }
    public Nullable<int> soluotview { get; set; }
    public Nullable<int> soluotlike { get; set; }
    public Nullable<int> trangthaibaiviet { get; set; }
    public string linkbaiviet { get; set; }
    public Nullable<int> id_datlich { get; set; }
    public Nullable<System.DateTime> ngaydang { get; set; }
    public Nullable<long> X { get; set; }
}

public partial class SP_PHANTRANGHOIDAP_Result
{
    public int id_cauhoitraloi { get; set; }
    public string cauhoi { get; set; }
    public string traloi { get; set; }
    public Nullable<System.DateTime> ngayhoi { get; set; }
    public Nullable<System.DateTime> ngaytraloi { get; set; }
    public Nullable<int> trangthai { get; set; }
    public Nullable<int> luotxem { get; set; }
    public Nullable<int> id_nguoitraloi { get; set; }
    public Nullable<int> id_chuyenmuc { get; set; }
    public string loaicauhoi { get; set; }
    public Nullable<int> id_nguoihoi { get; set; }
    public string filedinhkem { get; set; }
    public Nullable<bool> statusRepQuestion { get; set; }
    public string fileQuestion { get; set; }
    public string linkcauhoi { get; set; }
    public string tieudecauhoi { get; set; }
    public string tendaydu { get; set; }
    public Nullable<long> X { get; set; }
}

public partial class SP_THUVIEN_Result
{
    public int id_thuvien { get; set; }
    public string tieude { get; set; }
    public string gioithieu { get; set; }
    public string noidung { get; set; }
    public Nullable<System.DateTime> ngayupload { get; set; }
    public string tacgia { get; set; }
    public string loaithuvien { get; set; }
    public Nullable<int> id_taikhoan { get; set; }
    public Nullable<int> trangthaithuvien { get; set; }
    public Nullable<int> id_danhmuc { get; set; }
    public string linlthuvien { get; set; }
    public Nullable<int> luotxem { get; set; }
    public Nullable<long> X { get; set; }
}

public partial class SP_TINHUONGKHANCAP_Result
{
    public int id_huongdan { get; set; }
    public string tinhhuong { get; set; }
    public string cachxuly { get; set; }
    public Nullable<int> trangthai { get; set; }
    public Nullable<int> id_taikhoan { get; set; }
    public Nullable<System.DateTime> ngaytao { get; set; }
    public string tieude { get; set; }
    public string linktinhhuong { get; set; }
    public Nullable<long> X { get; set; }
}

public partial class spThongKe_Edit_Result
{
    public Nullable<long> HomNay { get; set; }
    public Nullable<long> HomQua { get; set; }
    public Nullable<long> TuanNay { get; set; }
    public Nullable<long> TuanTruoc { get; set; }
    public Nullable<long> ThangNay { get; set; }
    public Nullable<long> ThangTruoc { get; set; }
    public Nullable<long> TatCa { get; set; }
}
