//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class DataC50Entities : DbContext
{
    public DataC50Entities()
        : base("name=DataC50Entities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<LogHeThong_6_2016> LogHeThong_6_2016 { get; set; }
    public virtual DbSet<LogHeThong_6_2017> LogHeThong_6_2017 { get; set; }
    public virtual DbSet<Menu_Client> Menu_Client { get; set; }
    public virtual DbSet<NhomAdmin> NhomAdmin { get; set; }
    public virtual DbSet<NhomQuyen> NhomQuyen { get; set; }
    public virtual DbSet<QuanLyBanner> QuanLyBanner { get; set; }
    public virtual DbSet<QuanLyFileUpload> QuanLyFileUpload { get; set; }
    public virtual DbSet<QuanLyThuMuc> QuanLyThuMuc { get; set; }
    public virtual DbSet<TaiKhoan> TaiKhoan { get; set; }
    public virtual DbSet<TB_ThongKe> TB_ThongKe { get; set; }
    public virtual DbSet<tbl_Baiviet> tbl_Baiviet { get; set; }
    public virtual DbSet<tbl_BaiVietTrangGioiThieu> tbl_BaiVietTrangGioiThieu { get; set; }
    public virtual DbSet<tbl_BieuDo> tbl_BieuDo { get; set; }
    public virtual DbSet<tbl_CapBac> tbl_CapBac { get; set; }
    public virtual DbSet<tbl_CauhoiTraLoi> tbl_CauhoiTraLoi { get; set; }
    public virtual DbSet<tbl_ChiTietThuVien> tbl_ChiTietThuVien { get; set; }
    public virtual DbSet<tbl_ChuKyHienThiBanner> tbl_ChuKyHienThiBanner { get; set; }
    public virtual DbSet<tbl_ChuKyHienThiQuangCao> tbl_ChuKyHienThiQuangCao { get; set; }
    public virtual DbSet<tbl_ChuyenMucLuaChon> tbl_ChuyenMucLuaChon { get; set; }
    public virtual DbSet<tbl_Danhsachbanglog> tbl_Danhsachbanglog { get; set; }
    public virtual DbSet<tbl_DanhSachCanBo> tbl_DanhSachCanBo { get; set; }
    public virtual DbSet<tbl_DanhSachChucVu> tbl_DanhSachChucVu { get; set; }
    public virtual DbSet<tbl_DanhSachTongDai> tbl_DanhSachTongDai { get; set; }
    public virtual DbSet<tbl_DapAnThamDo> tbl_DapAnThamDo { get; set; }
    public virtual DbSet<tbl_DatLich> tbl_DatLich { get; set; }
    public virtual DbSet<tbl_DonVicongTac> tbl_DonVicongTac { get; set; }
    public virtual DbSet<tbl_donvithoigianbieudo> tbl_donvithoigianbieudo { get; set; }
    public virtual DbSet<tbl_Hinhthucphamtoi> tbl_Hinhthucphamtoi { get; set; }
    public virtual DbSet<tbl_HinhthucTraLoi> tbl_HinhthucTraLoi { get; set; }
    public virtual DbSet<tbl_Hosovuan> tbl_Hosovuan { get; set; }
    public virtual DbSet<tbl_HuongDanSuLyTinhHuong> tbl_HuongDanSuLyTinhHuong { get; set; }
    public virtual DbSet<tbl_LichHienThiThamDoYKien> tbl_LichHienThiThamDoYKien { get; set; }
    public virtual DbSet<tbl_LienKetHopTac> tbl_LienKetHopTac { get; set; }
    public virtual DbSet<tbl_Loaibieudo> tbl_Loaibieudo { get; set; }
    public virtual DbSet<tbl_LogHeThong> tbl_LogHeThong { get; set; }
    public virtual DbSet<tbl_LogResetMatKhau> tbl_LogResetMatKhau { get; set; }
    public virtual DbSet<tbl_logtraloithamdo> tbl_logtraloithamdo { get; set; }
    public virtual DbSet<tbl_Menu> tbl_Menu { get; set; }
    public virtual DbSet<tbl_quangcao> tbl_quangcao { get; set; }
    public virtual DbSet<tbl_QuyenSuDungFile> tbl_QuyenSuDungFile { get; set; }
    public virtual DbSet<tbl_ThamDoYKien> tbl_ThamDoYKien { get; set; }
    public virtual DbSet<tbl_Thongtinthoitiet> tbl_Thongtinthoitiet { get; set; }
    public virtual DbSet<tbl_Thongtintoipham> tbl_Thongtintoipham { get; set; }
    public virtual DbSet<tbl_ThuVienClient> tbl_ThuVienClient { get; set; }
    public virtual DbSet<tbl_TinBaoCongDan> tbl_TinBaoCongDan { get; set; }
    public virtual DbSet<tbl_TinhThanh> tbl_TinhThanh { get; set; }
    public virtual DbSet<tbl_VanBan> tbl_VanBan { get; set; }
    public virtual DbSet<tbl_Vitribv> tbl_Vitribv { get; set; }
    public virtual DbSet<tbl_VitriQuangCao> tbl_VitriQuangCao { get; set; }
    public virtual DbSet<tbl_ViTriVanBan> tbl_ViTriVanBan { get; set; }
    public virtual DbSet<tbl_Ykienbandoc> tbl_Ykienbandoc { get; set; }
    public virtual DbSet<Vitri_Menu> Vitri_Menu { get; set; }

    public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
    {
        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));

        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));

        var versionParameter = version.HasValue ?
            new ObjectParameter("version", version) :
            new ObjectParameter("version", typeof(int));

        var definitionParameter = definition != null ?
            new ObjectParameter("definition", definition) :
            new ObjectParameter("definition", typeof(byte[]));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
    }

    public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
    {
        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));

        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));

        var versionParameter = version.HasValue ?
            new ObjectParameter("version", version) :
            new ObjectParameter("version", typeof(int));

        var definitionParameter = definition != null ?
            new ObjectParameter("definition", definition) :
            new ObjectParameter("definition", typeof(byte[]));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
    }

    public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
    {
        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));

        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
    }

    public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
    {
        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));

        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
    }

    public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
    {
        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));

        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
    }

    public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
    {
        var diagramnameParameter = diagramname != null ?
            new ObjectParameter("diagramname", diagramname) :
            new ObjectParameter("diagramname", typeof(string));

        var owner_idParameter = owner_id.HasValue ?
            new ObjectParameter("owner_id", owner_id) :
            new ObjectParameter("owner_id", typeof(int));

        var new_diagramnameParameter = new_diagramname != null ?
            new ObjectParameter("new_diagramname", new_diagramname) :
            new ObjectParameter("new_diagramname", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
    }

    public virtual int sp_upgraddiagrams()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
    }

    public virtual ObjectResult<sp_loadall_tintucsukien_Result> sp_loadall_tintucsukien(Nullable<int> id, Nullable<int> currPage, Nullable<int> recodperpage, ObjectParameter totalCount)
    {
        var idParameter = id.HasValue ?
            new ObjectParameter("id", id) :
            new ObjectParameter("id", typeof(int));

        var currPageParameter = currPage.HasValue ?
            new ObjectParameter("currPage", currPage) :
            new ObjectParameter("currPage", typeof(int));

        var recodperpageParameter = recodperpage.HasValue ?
            new ObjectParameter("recodperpage", recodperpage) :
            new ObjectParameter("recodperpage", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loadall_tintucsukien_Result>("sp_loadall_tintucsukien", idParameter, currPageParameter, recodperpageParameter, totalCount);
    }

    public virtual int sp_loalall_log(Nullable<int> idloai, Nullable<int> idlog, Nullable<int> sessionid, string type, string type2, Nullable<int> currPage, Nullable<int> recodperpage, string nametable, ObjectParameter totalCount)
    {
        var idloaiParameter = idloai.HasValue ?
            new ObjectParameter("idloai", idloai) :
            new ObjectParameter("idloai", typeof(int));

        var idlogParameter = idlog.HasValue ?
            new ObjectParameter("idlog", idlog) :
            new ObjectParameter("idlog", typeof(int));

        var sessionidParameter = sessionid.HasValue ?
            new ObjectParameter("sessionid", sessionid) :
            new ObjectParameter("sessionid", typeof(int));

        var typeParameter = type != null ?
            new ObjectParameter("type", type) :
            new ObjectParameter("type", typeof(string));

        var type2Parameter = type2 != null ?
            new ObjectParameter("type2", type2) :
            new ObjectParameter("type2", typeof(string));

        var currPageParameter = currPage.HasValue ?
            new ObjectParameter("currPage", currPage) :
            new ObjectParameter("currPage", typeof(int));

        var recodperpageParameter = recodperpage.HasValue ?
            new ObjectParameter("recodperpage", recodperpage) :
            new ObjectParameter("recodperpage", typeof(int));

        var nametableParameter = nametable != null ?
            new ObjectParameter("nametable", nametable) :
            new ObjectParameter("nametable", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_loalall_log", idloaiParameter, idlogParameter, sessionidParameter, typeParameter, type2Parameter, currPageParameter, recodperpageParameter, nametableParameter, totalCount);
    }

    public virtual ObjectResult<spThongKe_Edit_Result> spThongKe_Edit()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spThongKe_Edit_Result>("spThongKe_Edit");
    }

    public virtual ObjectResult<SP_PHANTRANGHOIDAP_Result> SP_PHANTRANGHOIDAP(Nullable<int> trangthai, string noidung, Nullable<int> linhvuc, string tacgia, string dateS, string dateE, Nullable<int> currPage, Nullable<int> recodperpage, ObjectParameter totalCount)
    {
        var trangthaiParameter = trangthai.HasValue ?
            new ObjectParameter("trangthai", trangthai) :
            new ObjectParameter("trangthai", typeof(int));

        var noidungParameter = noidung != null ?
            new ObjectParameter("noidung", noidung) :
            new ObjectParameter("noidung", typeof(string));

        var linhvucParameter = linhvuc.HasValue ?
            new ObjectParameter("linhvuc", linhvuc) :
            new ObjectParameter("linhvuc", typeof(int));

        var tacgiaParameter = tacgia != null ?
            new ObjectParameter("tacgia", tacgia) :
            new ObjectParameter("tacgia", typeof(string));

        var dateSParameter = dateS != null ?
            new ObjectParameter("dateS", dateS) :
            new ObjectParameter("dateS", typeof(string));

        var dateEParameter = dateE != null ?
            new ObjectParameter("dateE", dateE) :
            new ObjectParameter("dateE", typeof(string));

        var currPageParameter = currPage.HasValue ?
            new ObjectParameter("currPage", currPage) :
            new ObjectParameter("currPage", typeof(int));

        var recodperpageParameter = recodperpage.HasValue ?
            new ObjectParameter("recodperpage", recodperpage) :
            new ObjectParameter("recodperpage", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PHANTRANGHOIDAP_Result>("SP_PHANTRANGHOIDAP", trangthaiParameter, noidungParameter, linhvucParameter, tacgiaParameter, dateSParameter, dateEParameter, currPageParameter, recodperpageParameter, totalCount);
    }

    public virtual ObjectResult<SP_DANHSACHTONGDAI_Result> SP_DANHSACHTONGDAI(Nullable<int> trangthai, string noidung, Nullable<int> currPage, Nullable<int> recodperpage, ObjectParameter totalCount)
    {
        var trangthaiParameter = trangthai.HasValue ?
            new ObjectParameter("trangthai", trangthai) :
            new ObjectParameter("trangthai", typeof(int));

        var noidungParameter = noidung != null ?
            new ObjectParameter("noidung", noidung) :
            new ObjectParameter("noidung", typeof(string));

        var currPageParameter = currPage.HasValue ?
            new ObjectParameter("currPage", currPage) :
            new ObjectParameter("currPage", typeof(int));

        var recodperpageParameter = recodperpage.HasValue ?
            new ObjectParameter("recodperpage", recodperpage) :
            new ObjectParameter("recodperpage", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DANHSACHTONGDAI_Result>("SP_DANHSACHTONGDAI", trangthaiParameter, noidungParameter, currPageParameter, recodperpageParameter, totalCount);
    }

    public virtual ObjectResult<SP_TINHUONGKHANCAP_Result> SP_TINHUONGKHANCAP(Nullable<int> trangthai, string noidung, Nullable<int> currPage, Nullable<int> recodperpage, ObjectParameter totalCount)
    {
        var trangthaiParameter = trangthai.HasValue ?
            new ObjectParameter("trangthai", trangthai) :
            new ObjectParameter("trangthai", typeof(int));

        var noidungParameter = noidung != null ?
            new ObjectParameter("noidung", noidung) :
            new ObjectParameter("noidung", typeof(string));

        var currPageParameter = currPage.HasValue ?
            new ObjectParameter("currPage", currPage) :
            new ObjectParameter("currPage", typeof(int));

        var recodperpageParameter = recodperpage.HasValue ?
            new ObjectParameter("recodperpage", recodperpage) :
            new ObjectParameter("recodperpage", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TINHUONGKHANCAP_Result>("SP_TINHUONGKHANCAP", trangthaiParameter, noidungParameter, currPageParameter, recodperpageParameter, totalCount);
    }

    public virtual ObjectResult<SP_THUVIEN_Result> SP_THUVIEN(Nullable<int> trangthai, string noidung, string tab, Nullable<int> currPage, Nullable<int> recodperpage, ObjectParameter totalCount)
    {
        var trangthaiParameter = trangthai.HasValue ?
            new ObjectParameter("trangthai", trangthai) :
            new ObjectParameter("trangthai", typeof(int));

        var noidungParameter = noidung != null ?
            new ObjectParameter("noidung", noidung) :
            new ObjectParameter("noidung", typeof(string));

        var tabParameter = tab != null ?
            new ObjectParameter("tab", tab) :
            new ObjectParameter("tab", typeof(string));

        var currPageParameter = currPage.HasValue ?
            new ObjectParameter("currPage", currPage) :
            new ObjectParameter("currPage", typeof(int));

        var recodperpageParameter = recodperpage.HasValue ?
            new ObjectParameter("recodperpage", recodperpage) :
            new ObjectParameter("recodperpage", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_THUVIEN_Result>("SP_THUVIEN", trangthaiParameter, noidungParameter, tabParameter, currPageParameter, recodperpageParameter, totalCount);
    }

    public virtual ObjectResult<SP_LOADDANHSACHBAIVIET_Result> SP_LOADDANHSACHBAIVIET(Nullable<int> idDM, Nullable<int> trangthai, Nullable<System.DateTime> ngaydang, Nullable<int> currPage, Nullable<int> recodperpage, ObjectParameter totalCount)
    {
        var idDMParameter = idDM.HasValue ?
            new ObjectParameter("idDM", idDM) :
            new ObjectParameter("idDM", typeof(int));

        var trangthaiParameter = trangthai.HasValue ?
            new ObjectParameter("trangthai", trangthai) :
            new ObjectParameter("trangthai", typeof(int));

        var ngaydangParameter = ngaydang.HasValue ?
            new ObjectParameter("ngaydang", ngaydang) :
            new ObjectParameter("ngaydang", typeof(System.DateTime));

        var currPageParameter = currPage.HasValue ?
            new ObjectParameter("currPage", currPage) :
            new ObjectParameter("currPage", typeof(int));

        var recodperpageParameter = recodperpage.HasValue ?
            new ObjectParameter("recodperpage", recodperpage) :
            new ObjectParameter("recodperpage", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LOADDANHSACHBAIVIET_Result>("SP_LOADDANHSACHBAIVIET", idDMParameter, trangthaiParameter, ngaydangParameter, currPageParameter, recodperpageParameter, totalCount);
    }
}
